<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Mon, 02 Dec 2013 01:55:26 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'currencyid' => '1',
    'currencycountryid' => '225',
    'currencycouregid' => NULL,
    'currencycode' => 'GBP',
    'currencyconvertercode' => NULL,
    'currencyname' => 'Default Currency',
    'currencyexchangerate' => '1.0000000000',
    'currencystring' => '$',
    'currencystringposition' => 'left',
    'currencydecimalstring' => '.',
    'currencythousandstring' => ',',
    'currencydecimalplace' => '2',
    'currencylastupdated' => '1385949314',
    'currencyisdefault' => '1',
    'currencystatus' => '1',
  ),
  'default' => '1',
);
