<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Mon, 02 Dec 2013 02:34:21 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    2 => 
    array (
      'pagetitle' => 'Shipping & Returns',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '2',
      'pagecustomersonly' => '0',
    ),
    1 => 
    array (
      'pagetitle' => 'RSS Syndication',
      'pagetype' => '0',
      'pagelink' => '',
      'pageparentid' => '0',
      'pageid' => '1',
      'pagecustomersonly' => '0',
    ),
  ),
  'defaultPage' => false,
);
