<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Sat, 25 Jan 2014 14:41:34 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    2 => 
    array (
      'pagetitle' => 'Shipping & Returns',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '2',
      'pagecustomersonly' => '0',
    ),
  ),
  'defaultPage' => false,
);
