<?php

/** Shopping Cart Data Store File **
  *
  * Generated: Fri, 06 Dec 2013 02:00:29 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    1 => 
    array (
      'categoryid' => '1',
      'catparentid' => '0',
      'catname' => 'Fragrance',
      'catdepth' => '0',
    ),
  ),
  1 => 
  array (
    3 => 
    array (
      'categoryid' => '3',
      'catparentid' => '1',
      'catname' => 'For Her',
      'catdepth' => '1',
    ),
    2 => 
    array (
      'categoryid' => '2',
      'catparentid' => '1',
      'catname' => 'For Him',
      'catdepth' => '1',
    ),
  ),
);
